### ISSUE TITLE
Progress bar while uploading not working correctly

### ISSUE THREAD

**Issue by hvijay3** [hvijay3/Piccolo#1]
Hey, nice work but when I am trying to upload an image, the progress bar gets stuck. Please look into it and find attached the screenshot.
Harshit.
![2017-09-28](https://user-images.githubusercontent.com/17895194/30951312-3c07a0c6-a3f0-11e7-89b3-d3b74af0a814.png)

**Comment by 19ankits** [comment]
Addressed the bug in commit #75f98e2. Was missing the status field in the html file for rendering from the component.
