### ISSUE TITLE
Adding User-Specific image-view feature . 

### ISSUE THREAD

**Issue by hvijay3** [hvijay3/Piccolo#10]
When user 1 logins into the application. He should just see his images i.e images uploaded by him.

**Comment by 19ankits** [comment]
Right now we are not saving any user specific details hence the issue. In order to do so, we will have to add new attributes to the upload model such as user-id etc while saving into the database.

**Comment by hvijay3** [comment]
Ok , then the same attribute we have to pass when we are retrieving images from database. It's like adding one more level hierarchy.

**Comment by hvijay3** [comment]
Resolved in commit fb5c3ba5d70249985f03d5c1e14a7f41cb199abb
