### ISSUE TITLE
Error while importing NgModules from @angular/material

### ISSUE THREAD

**Issue by 19ankits** [hvijay3/Piccolo#14]
After installing angular/material, angular/cdk and @angular/animations, I was having issues during import in the app.module.ts saying cannot export NgModules say MdCardModule for instance 

I'm using "2.0.0-beta.12" as seen in the "package.json" file.

**Comment by 19ankits** [comment]
Based on what I found, we have to replace the "Md" prefix with "Mat" in the app.module.ts to get rid of this issue.
Refer to the deprecation of "md" under this url
https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta11-carapace-parapet-2017-09-21

Also you may not have to upgrade to "2.0.0-beta.12", if currently you're on "2.0.0-beta.11", because it has both backward and forward compatibility. In short the beta.11 works with both "Md" and "Mat" prefixes but to have uniformity across code base I have modified everywhere to "Mat".

Let me know your view points on this if any.

**Comment by hvijay3** [comment]
Yes , you are right I am currently using version 2.0.0-beta.11 for which it works.

**Comment by 19ankits** [comment]
As agreed, updated the versions across all files, hence closing it now
