### ISSUE TITLE
Image List doesn't show a list of images after successful login

### ISSUE THREAD

**Issue by 19ankits** [hvijay3/Piccolo#2]
Although the Upload functionality successfully uploads the files into Firebase database, those are not displayed over the dashboard after login. To verify if the upload was successful, you can always check the Firebase DB untill the progress bar issue is resolved.

Ankit.
![screen shot 2017-09-28 at 11 34 17 am](https://user-images.githubusercontent.com/22759934/30975175-93ce801e-a43f-11e7-9e09-4123dec2be47.png)

**Comment by hvijay3** [comment]
Fixed it in commit 37723bdf62275061bf4b0bdf7161f3d3664f7578. Issue was due to wrong variable used in imagelist-component.ts
