### ISSUE TITLE
Comments styling . If possible then author name with comment.

### ISSUE THREAD

**Issue by hvijay3** [hvijay3/Piccolo#25]

**Comment by rahul-2-c** [comment]
Added styling to comments section. Fix was submitted via commit 5ca2861.

**Comment by rahul-2-c** [comment]
Currently, uid is displayed instead of author username. I am working on displaying username instead of uid.

**Comment by rahul-2-c** [comment]
Added code to display username of  comment author instead of uid. 

Opening a separate new issue for likes display for better tracking.

**Comment by rahul-2-c** [comment]
Fix submitted via commit 6a56235.
