### ISSUE TITLE
Fixes required in the Like/Dislike feature with Search and Follow functionality added

### ISSUE THREAD

**Issue by 19ankits** [hvijay3/Piccolo#29]
Found a bug that is imminent in future in the Like/Dislike feature with the on-going implrementation of search and Follow functionality. 
So here's the thing, "Like" feature as of now increments the count only for the images owned by the logged in user. In other words, "Like" count gets incremented correctly only when a user likes his/her own upload images. This is because we have logged in userId (retrieved from ImageService) added in the path before updating the count in the database.

**Comment by rahul-2-c** [comment]
Fix provided in commit f3f8f5c.
